name: Generate pre release
on:
  workflow_call:
    inputs:
      matrix_dominio:
        type: string
        description: matrix_dominio
      execute_matrix:
        type: boolean
jobs:
  only_job:
    runs-on: ubuntu-latest
    if: ${{ inputs.execute_matrix == true }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: ${{ inputs.matrix_dominio }}
      
      - name: Outputs 
        id: outputs_matrix
        run: |
          last_tag_repo=$(jq -r '.last_tag_repo' ${{ inputs.matrix_dominio }}.json)
          next_tag_repo=$(jq -r '.next_tag_repo' ${{ inputs.matrix_dominio }}.json)
          cat ${{ inputs.matrix_dominio }}.json
          last_stable_release=$(jq -r '.last_stable_release' ${{ inputs.matrix_dominio }}.json)
          echo "last_tag_repo=$last_tag_repo" >> $GITHUB_OUTPUT
          echo "next_tag_repo=$next_tag_repo" >> $GITHUB_OUTPUT
          echo "last_stable_release=$last_stable_release" >> $GITHUB_OUTPUT
          echo "domain=$(echo $next_tag_repo | cut -d'-' -f1)" >> $GITHUB_OUTPUT
          echo "subdomain=$(echo $next_tag_repo | cut -d'-' -f2)" >> $GITHUB_OUTPUT
          echo "destination=$(echo $next_tag_repo | cut -d'-' -f3)" >> $GITHUB_OUTPUT

      - name: Push new Tag ReleaseCandidate
        id: tag_release_candidate
        run: |
          tag='${{ steps.outputs_matrix.outputs.next_tag_repo }}'
          message='${{ steps.outputs_matrix.outputs.next_tag_repo }}'
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
          echo "TAG_RELEASE_CANDIDATE=$tag" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Changelog
        id: build_changelog
        working-directory: ./.github/scripts
        run: |
          chmod +x get_changelog.sh
          {
            echo 'changelog<<EOF'
            ./get_changelog.sh "${{ steps.outputs_matrix.outputs.last_stable_release || '' }}" "${{ steps.outputs_matrix.outputs.next_tag_repo }}" ${{github.repository}} false true "-- ${{steps.outputs_matrix.outputs.domain}}/${{steps.outputs_matrix.outputs.subdomain}}/${{steps.outputs_matrix.outputs.destination}}"
             echo EOF
          } >> "GITHUB_OUTPUT"

      - name: Create PreRelease        
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: '${{ steps.outputs_matrix.outputs.next_tag_repo }}'
          release_name: '${{ steps.outputs_matrix.outputs.next_tag_repo }}'
          body: |
            Actor: ${{ env.USER_ACTOR }}
            ActionRunner: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ${{ steps.build_changelog.outputs.changelog }}
