name: Get matrix status
on:
  workflow_call:
    inputs:
      status:
        type: string
        description: Matrix status
      job_name:
        type: string
      run_id:
        required: false 
        type: string               
      run_attempt:
        required: false
        type: string

    outputs:
      matrix_status:
        description: "List of matrix status"
        value: ${{ jobs.getMatrixStatus.outputs.matrix_status }}
jobs:
  getMatrixStatus:
    runs-on: ubuntu-latest
    outputs:
      matrix_status: ${{ steps.get_matrix_status.outputs.matrix_status }}
    steps:
      - name: Get matrix status
        id: get_matrix_status
        run: |
          list_matrix_status=""
          page=1       
          num_jobs=1

          while [ $num_jobs -gt 0 ]; do
            URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ inputs.run_id || github.run_id}}/attempts/${{ inputs.run_attempt || github.run_attempt }}/jobs?per_page=100&page=$page"
            jobs=$(curl -s -H "Authorization: Bearer ${{  secrets.GITHUB_TOKEN  }}" "$URL")
            num_jobs=$(echo "$jobs" | jq '.jobs | length')         
            matrix_status=$(echo "$jobs" | jq -r --arg status "${{ inputs.status }}" '.jobs | map(select(.conclusion as $e | ($status | split(",") | index($e)) and (.name | tostring | startswith("${{ inputs.job_name}}")))) | map(.name) | join("|")')
            list_matrix_status="$list_matrix_status $matrix_status"            
            echo "page: $page  - num_jobs: $num_jobs"
            page=$((page + 1 ))
          done

          echo $list_matrix_status
          list_matrix_status=$(echo "$list_matrix_status" | sed 's/^ *//;s/ *$//')
          echo "matrix_status=$list_matrix_status" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
